banner: '+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

  |A|u|t|h|o|r| |:| |R|A|V|I| |T|E|J|A| |M|A|N|D|A|P|A|T|I|

  +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ '
locations:
- hyd
- blr
